apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nais-sensu.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "nais-sensu.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "nais-sensu.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "nais-sensu.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: LOG_LEVEL
            value: "{{ .Values.loglevel }}"
          - name: RABBITMQ_HOST
            value: "{{ .Values.rabbitmq.host }}"
          - name: RABBITMQ_PORT
            value: "{{ .Values.rabbitmq.port }}"
          - name: RABBITMQ_VHOST
            value: "{{ .Values.rabbitmq.vhost }}"
          - name: RABBITMQ_USER
            value: "{{ .Values.rabbitmq.user }}"
          - name: RABBITMQ_PASSWORD
            value: "{{ .Values.rabbitmq.password }}"
        ports:
          - containerPort: 3030
            protocol: TCP
