---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "nais-sensu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Values.service.name }}"
spec:
  type: ClusterIP
  selector:
    app: {{ template "nais-sensu.name" . }}
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
